### ISSUE TITLE
White Shadow Borders Appearing in Light Mode When Using Dark Reader Extension (UI Bug)

### ISSUE THREAD

**Issue by mehrazino** [imfing/hextra#626]
## **Description**
When the website theme is in Light Mode and the [Dark Reader](https://darkreader.org/) extension is enabled (darkening the site), white shadow borders appear around certain UI elements. This issue affects elements such as the language selector in the bottom-left corner and the "Edit this page on GitHub" link on the right sidebar. The borders are unintended and disrupt the intended design of the page.

## **Steps To Reproduce**
1. Set the website theme to **Light Mode**.
2. Enable the Dark Reader extension in your browser (ensure it's in dark mode).
3. Navigate to any website using the Hextra theme.
4. Observe the white shadow borders appearing around certain UI elements, such as the language selector and the "Edit this page on GitHub" link, on any page.

## **Expected Behavior**
There should be no unwanted white shadow borders when using Light Mode with the Dark Reader extension in dark mode. The UI should appear clean and as intended with no visual distractions.

## **Actual Behavior**
White shadow borders appear around certain UI elements when the website is in Light Mode and Dark Reader is enabled in dark mode.

## **Environment**
- **Browser/OS:** Chrome and Edge  
- **Theme Version:** v0.9.5  

## **Additional Context**
I’ve noticed this issue in both Chrome and Edge. I’m not sure if the problem is with the Dark Reader extension itself or if it's due to incompatibility between the theme and this widely-used extension.

## **Screenshots**
![Image](https://github.com/user-attachments/assets/c6048c3c-30fd-4c68-a6b4-6fe98e76f512)

**Comment by imfing** [comment]
this should be fixed in #632 

<img width="1476" alt="Image" src="https://github.com/user-attachments/assets/56b3a89e-fcc2-4443-8a01-e6ce64c3ffd1" />

**Comment by mehrazino** [comment]
> this should be fixed in [#632](https://github.com/imfing/hextra/pull/632)
> 
> <img alt="Image" width="1476" src="https://private-user-images.githubusercontent.com/5097752/428408701-56b3a89e-fcc2-4443-8a01-e6ce64c3ffd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMzNjEwMzQsIm5iZiI6MTc0MzM2MDczNCwicGF0aCI6Ii81MDk3NzUyLzQyODQwODcwMS01NmIzYTg5ZS1mY2MyLTQ0NDMtOGEwMS1lNmNlNjRjM2ZmZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMzBUMTg1MjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQwZWEyNDBlMDFkZjM0MmNkNjU1Y2UwODA3YTcyMzMyNDQ0ODk4ZmJiMmI1MGQ2YTE1YjNmN2Q0MGJhMGJlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1xdaTFUuOjeTgDg8xTnPsOB2n8QWBma90_7YWlhDHC0">

Hi. Thank you for your efforts, but unfortunately, I still see this issue (on https://imfing.github.io/hextra/docs/).
It occurs in both Chrome and Edge.
Just to be sure, I refreshed the browser and the extension but i still see this issue.

Chrome Version 134.0.6998.178 (Official Build) (64-bit)
Microsoft Edge Version 134.0.3124.93 (Official build) (64-bit)
Dark Reader Extension Version: 4.9.105

**Comment by imfing** [comment]
@mehrazino try the latest (main branch) version -> https://imfing.github.io/hextra/versions/latest/docs/

Note: this hasn’t been released yet, so the docs site (https://imfing.github.io/hextra/docs/) is still using hextra version 0.9.7

**Comment by mehrazino** [comment]
> [@mehrazino](https://github.com/mehrazino) try the latest (main branch) version -> https://imfing.github.io/hextra/versions/latest/docs/
> 
> Note: this hasn’t been released yet, so the docs site (https://imfing.github.io/hextra/docs/) is still using hextra version 0.9.7

@imfing 
Oh, yes! it's completely fixed.
Thank you again.
